/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "set.language": [],
    "home": [],
    "laravel-folio": [
        {
            "name": "fallbackPlaceholder",
            "required": true
        }
    ]
}
}
export {};
