<script lang="ts" setup>
import {onMounted, ref, nextTick} from 'vue'
import {Icon} from '@iconify/vue';
import UICard from '@/Components/UI/Card/Index.vue'
import {randomID} from '@/utils/helpers'
import UIMenuDropdown from '@/Components/UI/Menu/Dropdown/Index.vue'
import UIMenuDropdownItem from '@/Components/UI/Menu/Dropdown/Item.vue'

onMounted(() => {
    initFlowbite();
})

defineProps({
    size: {
        type: String,
        default: 'sm'
    },
    title: {
        type: String,
        default: null
    },
})

const slots = defineSlots()

const generatedID = randomID(15)

let showCard = ref(true)
let showPanel = ref(true)
let fullScreen = ref(false)

//const card = ref<HTMLElement | null>(null);

const togglePanel = () => {
    showPanel.value = !showPanel.value;
};
const closeCard = () => {
    showCard.value = false;
};
const toggleFullScreen = () => {
    fullScreen.value = !fullScreen.value;
};

const delayedFullScreen = () => {
    setTimeout(toggleFullScreen, 300);
}
const showPane = () => {
    showPanel.value = true;
}
const refreshPanel = () => {
    showPanel.value = false
    nextTick(() => {
        setTimeout(showPane, 500);
    });
};

const refreshCard = () => {
    showCard.value = false
    nextTick(() => {
        showCard.value = true;
    });
};
defineOptions({
    inheritAttrs: false
})
</script>
<template>
    <Transition>
        <UICard v-if="showCard" v-bind:size="size" v-bind:fullScreen="fullScreen" v-bind="$attrs">
            <!--Head-->
            <div class="flex justify-between p-4">
                <!--Left-->
                <div class="flex">
                    <h3 class="mb-4 text-xl font-semibold dark:text-white" v-if="title" v-text="title"></h3>
                </div>
                <!--Right-->
                <div class="flex">
                    <!-- Card Hint -->
                    <div
                        class="cursor-help inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5">
                        <svg v-bind:data-popover-target="`card-hint-${generatedID}`" data-popover-placement="bottom"
                             class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                             viewBox="0 0 20 20">
                            <path
                                d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"/>
                        </svg>
                        <div data-popover v-bind:id="`card-hint-${generatedID}`" role="tooltip"
                             class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                            <div class="p-3 space-y-2">
                                <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth
                                    -
                                    Incremental
                                </h3>
                                <p>Report helps navigate cumulative growth of community activities.
                                    Ideally,
                                    the
                                    chart
                                    should have a growing trend, as stagnating chart signifies a
                                    significant
                                    decrease of
                                    community activity.</p>
                                <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                                <p>For each date bucket, the all-time volume of activities is
                                    calculated.
                                    This
                                    means
                                    that activities in period n contain all activities up to period n,
                                    plus
                                    the
                                    activities generated by your community in period.</p>
                                <a href="#"
                                   class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read
                                    more
                                    <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true"
                                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                              stroke-width="2" d="m1 9 4-4-4-4"/>
                                    </svg>
                                </a>
                            </div>
                            <div data-popper-arrow></div>
                        </div>
                    </div>
                    <!--Card Menu -->
                    <div>
                        <UIMenuDropdown id="card-menu"
                                        class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5"
                                        menuClass="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700"
                                        v-bind:useArrow="false">
                            <template #trigger>
                                <Icon icon="tabler:dots-vertical" class="w-5 h-5"/>
                            </template>
                            <p
                                class="flex px-4 py-2 text-xs text-gray-700 uppercase dark:text-gray-200 dark:hover:text-white">
                                Card Settings</p>
                            <UIMenuDropdownItem as="a" v-bind:useLinkClass="false"
                                                class="flex px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                                                v-on:click.prevent="togglePanel" role="button">
                                <Icon icon="tabler:arrow-up" class="w-5 h-5 mr-2" v-show="showPanel"/>
                                <Icon icon="tabler:arrow-down" class="w-5 h-5 mr-2" v-show="!showPanel"/>
                                <span v-text="showPanel ? 'Hide Panel' : 'Show Panel'"></span>
                            </UIMenuDropdownItem>
                            <UIMenuDropdownItem as="a" v-bind:useLinkClass="false"
                                                class="flex px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                                                v-on:click.prevent="delayedFullScreen" role="button">
                                <Icon icon="tabler:arrows-maximize" class="w-5 h-5 mr-2" v-show="!fullScreen"/>
                                <Icon icon="tabler:arrows-minimize" class="w-5 h-5 mr-2" v-show="fullScreen"/>
                                <span v-text="fullScreen ? 'Minimize Card' : 'Maximize Card'"></span>
                            </UIMenuDropdownItem>
                            <UIMenuDropdownItem as="a" v-bind:useLinkClass="false"
                                                class="flex px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
                                                v-on:click.prevent="refreshPanel" role="button">
                                <Icon icon="tabler:refresh" class="w-5 h-5 mr-2"/>
                                <span>Refresh Card</span>
                            </UIMenuDropdownItem>
                            <UIMenuDropdownItem as="a" v-bind:useLinkClass="false"
                                                class="flex px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-red-500 dark:hover:text-red-600"
                                                v-on:click.prevent="closeCard" role="button">
                                <Icon icon="tabler:x" class="w-5 h-5 mr-2"/>
                                Remove Card
                            </UIMenuDropdownItem>
                        </UIMenuDropdown>
                    </div>
                </div>
            </div>
            <Transition>
                <!-- Panel -->
                <div v-show="showPanel">
                    <!--Body-->
                    <div class="flex flex-col items-center">
                        <slot/>
                    </div>
                    <!-- Footer -->
                    <template v-if="slots.footer">
                        <div class="flex justify-between p-4">
                            <slot name="footer"/>
                        </div>
                    </template>
                </div>
            </Transition>
        </UICard>
    </Transition>
</template>
<style>
.v-enter-active,
.v-leave-active {
    transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
    opacity: 0;
}
</style>
